baseURL = "https://alkatium.com/"
languageCode = "en-us"
title = "Alkatium"
theme = "airspace-hugo"

[languages]
  [languages.en]
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.fr]
    [languages.fr.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"
[params]
  home = "Home"
  
[menu]

#   [[menu.header]]
#     weight = 2
#     name = "Work"
#     url = "#portfolio-work"
  [[menu.header]]
    weight = 4
    name = "Services"
    url = "#service"
  [[menu.header]]
    weight = 6
    name = "About us"
    url = "#testimonial"
  [[menu.header]]
    weight = 6
    name = "Contact"
    url = "#contact-form"


  [[menu.footer]]
    weight = 2
    name = "Services"
    url = "#services"
  [[menu.footer]]
    weight = 3
    name = "About us"
    url = "#testimonial"
  [[menu.footer]]
    weight = 4
    name = "Contact us"
    url = "#contact-form"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "terms"

[params.slider]
  enable = true
  title = "IT consulting company"
  subtitle = "We love what we do because the time of machine learning is just beginning"
  bgImage = "img/background.jpg"
  btnText = "Discover Our Services"
  url = "#service"

[params.wrapper]
  enable = true
  image = "img/wrapper-img.png"
  title = "Alkatium"
  italic = "The IT consulting company"
  paragraph = "Alkatium is a very young company that wishes to make its knowledge available through collaborations. Current innovation in the IT world and more specifically in the field of machine learning is leading companies to improve their information systems and processes. Our company wants to provide adapted solutions in response to these improvements. In addition, Alkatium is strongly oriented towards opening the source code, i.e. free software."

[params.blog]
  enable = false
  title = "Get The Latest On What We're doing"
  subtitle = "Catch up with us, anytime and anywhere"

[params.feature]
  enable = false
  title = "We believe in great ideas"
  bgImage = "img/feature-bg.jpg"
  content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
  [params.feature.button]
    caption = "View Works"
    url = "#"

[params.citation]
  enable = true
  bgImage = "img/background.jpg"
  citation = "Don't seek to have events happen as you wish, but wish them to happen as they do happen, and all will be well with you."
  author = "Epictetus"
  [params.citation.button]
    url = "#"
    text = ""

[params.contact]
  enable = true
  title = "Contact us"
  subtitle = ""
  [params.contact.form]
    name = "Your name"
    email = "Your email"
    subject = "Your subject"
    message = "Your message"
    button = "Send message"
  [params.contact.box]
    title = "Stop by for a visit"
    address = "3 rue Kant, 59000 Lille, France"
    email = "contact@alkatium.com"
    phone = "+33 6 78 99 46 80"
    github = "https://github.com/alkatium"
  [params.contact.gmaps]
    title = "We Also Count in Google Maps"